spring:
  messages:
    basename: messages
    encoding: UTF-8
    fallback-to-system-locale: false
  datasource:
    url: jdbc:postgresql://localhost:5432/bachelor
    username: arsenart
    password:
    driver-class-name: org.postgresql.Driver
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
    properties:
      hibernate:
        format_sql: true
  mail:
    host: smtp.mailtrap.io
    port: 2525
    username: 0f9e58606c838b
    password: 7105bc4ba9f5c6
    properties:
      mail:
        smtp:
          auth: true
          starttls.enable: true

app:
  base-url: http://localhost:8080
  admin:
    email: admin@company.com
    password: admin123
